version: '3'
services:
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mydatabase"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
volumes:
  mysql_data:
